[package]
name = "waf-wordpress"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
waf-core = { path = "../waf-core" }
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
bytes.workspace = true
multer.workspace = true
futures-util.workspace = true
[dev-dependencies]
tokio.workspace = true
